# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_map.xdc

# Block Designs: bd/i2c_interface/i2c_interface.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface || ORIG_REF_NAME==i2c_interface} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_microblaze_0_0/i2c_interface_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_microblaze_0_0 || ORIG_REF_NAME==i2c_interface_microblaze_0_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_axi_uartlite_0_0/i2c_interface_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_axi_uartlite_0_0 || ORIG_REF_NAME==i2c_interface_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_axi_gpio_0_0/i2c_interface_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_axi_gpio_0_0 || ORIG_REF_NAME==i2c_interface_axi_gpio_0_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_dlmb_v10_0/i2c_interface_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_dlmb_v10_0 || ORIG_REF_NAME==i2c_interface_dlmb_v10_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_ilmb_v10_0/i2c_interface_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_ilmb_v10_0 || ORIG_REF_NAME==i2c_interface_ilmb_v10_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_dlmb_bram_if_cntlr_0/i2c_interface_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==i2c_interface_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_ilmb_bram_if_cntlr_0/i2c_interface_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==i2c_interface_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_lmb_bram_0/i2c_interface_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_lmb_bram_0 || ORIG_REF_NAME==i2c_interface_lmb_bram_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_xbar_0/i2c_interface_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_xbar_0 || ORIG_REF_NAME==i2c_interface_xbar_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_microblaze_0_axi_periph_0/i2c_interface_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_microblaze_0_axi_periph_0 || ORIG_REF_NAME==i2c_interface_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_microblaze_0_axi_intc_0/i2c_interface_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_microblaze_0_axi_intc_0 || ORIG_REF_NAME==i2c_interface_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_mdm_1_0/i2c_interface_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_mdm_1_0 || ORIG_REF_NAME==i2c_interface_mdm_1_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_clk_wiz_1_0/i2c_interface_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_clk_wiz_1_0 || ORIG_REF_NAME==i2c_interface_clk_wiz_1_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_rst_clk_wiz_1_100M_0/i2c_interface_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==i2c_interface_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/i2c_interface/ip/i2c_interface_axi_to_iic_0_0/i2c_interface_axi_to_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_interface_axi_to_iic_0_0 || ORIG_REF_NAME==i2c_interface_axi_to_iic_0_0} -quiet] -quiet

# XDC: /media/lifrankfan/CrucialX6/CameraDriverV2/CameraDriverV2.gen/sources_1/bd/i2c_interface/i2c_interface_ooc.xdc
