set_property PACKAGE_PIN N15 [get_ports Clk]
set_property PACKAGE_PIN C13 [get_ports led]
set_property PACKAGE_PIN B16 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN A16 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN H14 [get_ports scl]
set_property PACKAGE_PIN H13 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]

set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports sda]

set_property IOSTANDARD LVCMOS33 [get_ports sda_0]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports scl_0]
set_property PACKAGE_PIN N15 [get_ports clk_100MHz]
set_property PACKAGE_PIN E15 [get_ports sda_0]
set_property PACKAGE_PIN C13 [get_ports {gpio_rtl_0_tri_o[0]}]
set_property PACKAGE_PIN H14 [get_ports scl_0]
set_property PACKAGE_PIN J2 [get_ports reset_rtl_0]

